# Generated by Django 5.1.4 on 2024-12-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='usuarios',
            field=models.ManyToManyField(related_name='promocion_usuario', to='examen.usuario'),
        ),
    ]
