# Generated by Django 5.1.4 on 2024-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_alter_promocion_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
